name: DEBUG PATHS

on:
  push:
    branches: [main]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show real folders
        run: |
          echo "=== ROOT DIRECTORY ==="
          pwd
          ls -la
          echo "=== RECURSIVE LIST ==="
          ls -R .
